//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GYMEntities : DbContext
    {
        public GYMEntities()
            : base("name=GYMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coffe> Coffes { get; set; }
        public virtual DbSet<Diet> Diets { get; set; }
        public virtual DbSet<Meal> Meals { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Subscribtion> Subscribtions { get; set; }
        public virtual DbSet<Supplement> Supplements { get; set; }
        public virtual DbSet<TrainingDay> TrainingDays { get; set; }
        public virtual DbSet<TrainingLevel> TrainingLevels { get; set; }
        public virtual DbSet<TrainingWeek> TrainingWeeks { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
    }
}
