//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        public int MealID { get; set; }
        public Nullable<int> DietID { get; set; }
        public string Breakfast { get; set; }
        public string Snack1 { get; set; }
        public string Lunch { get; set; }
        public string Snack2 { get; set; }
        public string Dinner { get; set; }
        public string Day { get; set; }
    
        public virtual Diet Diet { get; set; }
    }
}
