//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int MemberID { get; set; }
        public string MemberName { get; set; }
        public Nullable<int> MemberAge { get; set; }
        public string MemberGender { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
        public Nullable<int> Paid { get; set; }
        public Nullable<int> RemainingAmount { get; set; }
        public Nullable<int> SubscribtionID { get; set; }
        public string Phone { get; set; }
    
        public virtual Subscribtion Subscribtion { get; set; }
    }
}
