//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftIncome
    {
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CoffeIncome { get; set; }
        public Nullable<int> SubscribesIncome { get; set; }
        public Nullable<int> ElectricityBills { get; set; }
        public Nullable<int> WaterBills { get; set; }
        public Nullable<int> GasBills { get; set; }
        public Nullable<int> OtherIncome { get; set; }
        public Nullable<int> Repairs { get; set; }
        public string Shift { get; set; }
        public int ShiftID { get; set; }
        public Nullable<int> NetProfit { get; set; }
    }
}
