//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingDay
    {
        public string DayName { get; set; }
        public string TargetMuscle { get; set; }
        public Nullable<int> Groups { get; set; }
        public Nullable<int> Repetations { get; set; }
        public byte[] Image { get; set; }
        public string TrainingDesc { get; set; }
        public Nullable<int> LevelID { get; set; }
        public int DayID { get; set; }
    
        public virtual TrainingLevel TrainingLevel { get; set; }
    }
}
