//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int WorkerID { get; set; }
        public string WorkerName { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> Birhtdate { get; set; }
        public string Shift { get; set; }
        public Nullable<int> Phone { get; set; }
    }
}
